#!/bin/bash
source ${XDG_CONFIG_HOME}/aliases/python2.aliases
source ${XDG_CONFIG_HOME}/aliases/ls.aliases
source ${XDG_CONFIG_HOME}/aliases/vagrant.aliases
source ${XDG_CONFIG_HOME}/aliases/git.aliases
# source ~${XDG_CONFIG_HOME}/aliases/pacman.sh
source ${XDG_CONFIG_HOME}/aliases/apt.sh
source ${XDG_CONFIG_HOME}/aliases/general.sh
source ${XDG_CONFIG_HOME}/aliases/vim.sh
