alias be='bundle exec'
alias beff='bundle exec rspec --fail-fast'
alias bep='bundle exec pry'
alias berc='bundle exec rails c'
alias beri='bundle exec ruby -Itest'
alias berr='bundle exec rspec'
alias bers='bundle exec rails s'
