alias be='bundle exec'
alias beff='bundle exec rspec --fail-fast'
alias bep='bundle exec pry'
alias berc='bundle exec rails c'
alias beri='bundle exec ruby -Itest'
alias berp='bundle exec rails s -p 5000'
alias berr='bundle exec rspec'
alias bers='bundle exec rails s'
alias heroku='/usr/bin/heroku'
alias hlogin='HEROKU_ORGANIZATION=thelevelup heroku login --sso'
alias robocop='bundle exec rubocop'
